using PanoramicData.NugetManagement.Models;
using PanoramicData.NugetManagement.Rules;
using PanoramicData.NugetManagement.Services;
using PanoramicData.NugetManagement.Web.Remediations;

namespace PanoramicData.NugetManagement.Test;

/// <summary>
/// Codacy's Agentlinter reads a file name in CLAUDE.md as a reference and reports it when its workspace
/// holds no such file — "Referenced file CONTRIBUTING.md not found in workspace" — whether or not the
/// repository has one. The v1.2 template named CONTRIBUTING.md twice, so every repository built from it
/// graded C with a High ErrorProne issue.
/// </summary>
public class ClaudeMdUnresolvedReferenceTests(ITestOutputHelper output) : TestWithOutput(output), IDisposable
{
	private const string _repository = "panoramicdata/TeamViewer.Api";

	/// <summary>
	/// The CLAUDE.md as generated by template v1.2, exactly as it sits in the estate's repositories.
	/// </summary>
	private const string _generatedV12 = """
		# CLAUDE.md

		Version: 1.2

		## Identity

		You are Claude Code, acting as a careful, security-conscious contributor to this repository,
		following Panoramic Data's engineering conventions.

		## About Panoramic Data

		Panoramic Data Limited is a software company. This repository is a NuGet package that it
		publishes. Its build, CI, versioning, licensing and community files are governed by the open
		source PanoramicData.NugetManagement tool (https://github.com/panoramicdata/PanoramicData.NugetManagement),
		which assesses repositories against a shared set of rules and can apply fixes automatically.
		Files such as CLAUDE.md, AGENTS.md, SECURITY.md and CONTRIBUTING.md may be created or updated
		by that tool.

		## Scope and boundaries

		- Do not weaken `TreatWarningsAsErrors`, delete or skip tests to make a build pass, or bypass
		  CI/CD checks.
		- Do not commit secrets, credentials, or API tokens.
		- Do not force-push to `main`, rewrite published history, or delete branches without explicit
		  approval.

		## Tools

		- Build and test with `dotnet build` / `dotnet test`.
		- Use `git` for version control, following `CONTRIBUTING.md` where present.

		## Shared instructions

		@.github/copilot-instructions.md
		@../PanoramicData.Skills/.github/skills/copilot-instructions.md

		The second import above is optional: if the private `PanoramicData.Skills` sibling repository
		is not checked out next to this one, Claude Code silently skips it.
		""";

	private readonly string _root = Directory.CreateTempSubdirectory("claudemd").FullName;

	public void Dispose()
	{
		Directory.Delete(_root, recursive: true);
		GC.SuppressFinalize(this);
	}

	[Fact]
	public void ShouldBeRegisteredForAi04()
		=> new RemediationRegistry().Get("AI-04").Should().NotBeNull();

	[Fact]
	public void TheCurrentTemplate_ShouldNameNoFileCodacyCannotFind()
		=> Standards.ClaudeMdContent.Should().NotContain("CONTRIBUTING.md");

	[Fact]
	public async Task ShouldPass_ForTheCurrentTemplate()
	{
		var result = await EvaluateAsync(Standards.ClaudeMdContent).ConfigureAwait(true);

		result.Passed.Should().BeTrue();
	}

	[Fact]
	public async Task ShouldBeNotApplicable_WhenThereIsNoClaudeMd()
	{
		var result = await EvaluateAsync(content: null).ConfigureAwait(true);

		result.Passed.Should().BeTrue();
		result.IsApplicable.Should().BeFalse("AI-01 reports the missing file");
	}

	[Fact]
	public async Task ShouldFail_ForTheGeneratedV12Template()
	{
		var result = await EvaluateAsync(_generatedV12).ConfigureAwait(true);

		result.Passed.Should().BeFalse();
		result.Advisory!.Data["remediation_type"].Should().Be("replace_regex_in_file");
		result.Advisory.Data["file"].Should().Be("CLAUDE.md");
		new RemediationRegistry().CanRemediate(result).Should().BeTrue();
	}

	[Fact]
	public async Task Fix_ShouldTurnTheGeneratedV12TemplateIntoTheCurrentOne()
	{
		// The estate's files are v1.2 as generated, so fixing them must land exactly on what a new
		// repository gets — otherwise the fix and the template drift apart.
		var fixedContent = await ApplyFixAsync(_generatedV12).ConfigureAwait(true);

		Normalise(fixedContent).Should().Be(Normalise(Standards.ClaudeMdContent));
		fixedContent.Should().NotContain("CONTRIBUTING.md");
	}

	[Fact]
	public async Task Fix_ShouldPassTheRuleAfterwards()
	{
		var fixedContent = await ApplyFixAsync(_generatedV12).ConfigureAwait(true);

		var after = await EvaluateAsync(fixedContent).ConfigureAwait(true);
		after.Passed.Should().BeTrue();
	}

	[Fact]
	public async Task Fix_ShouldKeepWhatARepositoryAddedToItsOwnClaudeMd()
	{
		const string addition = "## Repository notes\n\nThe TeamViewer token lives in the test secrets file.\n";
		var customised = Normalise(_generatedV12) + "\n\n" + addition;

		var fixedContent = await ApplyFixAsync(customised).ConfigureAwait(true);

		fixedContent.Should().Contain(addition.TrimEnd());
		fixedContent.Should().NotContain("CONTRIBUTING.md");
	}

	[Fact]
	public async Task ShouldNotFlagAHandWrittenMention_ItCannotRewrite()
	{
		// Only the two phrasings the template used are rewritten. A mention anyone wrote themselves is not
		// ours to edit, and failing on it would leave a Fix button that changes nothing.
		var result = await EvaluateAsync("# CLAUDE.md\n\nSee CONTRIBUTING.md before opening a pull request.\n").ConfigureAwait(true);

		result.Passed.Should().BeTrue();
	}

	private async Task<string> ApplyFixAsync(string content)
	{
		var failing = await EvaluateAsync(content).ConfigureAwait(true);
		failing.Passed.Should().BeFalse();

		var path = Path.Combine(_root, "CLAUDE.md");
		File.WriteAllText(path, content);

		var applied = new List<string>();
		new RemediationRegistry().Get("AI-04")!.Apply(_root, failing, applied, null);

		applied.Should().ContainSingle().Which.Should().Be("CLAUDE.md");
		return File.ReadAllText(path);
	}

	private static string Normalise(string text) => text.Replace("\r\n", "\n").Trim();

	private static async Task<RuleResult> EvaluateAsync(string? content)
	{
		var files = content is null
			? new Dictionary<string, string>()
			: new Dictionary<string, string> { ["CLAUDE.md"] = content };

		var context = new RepositoryContext
		{
			FullName = _repository,
			Name = "TeamViewer.Api",
			DefaultBranch = "main",
			Options = new RepoOptions(),
			FilePaths = [.. files.Keys],
			FileContents = files
		};

		return await RuleRegistry.Rules.Single(r => r.RuleId == "AI-04")
			.EvaluateAsync(context, CancellationToken.None)
			.ConfigureAwait(false);
	}
}
